mysql:
  image: mysql
  ports:
   - "3307:3306"
  volumes:
   - ~/docker/mysql/data:/var/lib/mysql
   - ~/docker/mysql/cnf/my.cnf:/etc/mysql/conf.d/mysqld.cnf
discovery:
  image: sit/sit-base-service-center
  ports:
   - "9099:9099"
token-service:
  image: sit/sit-base-token-service
  links:
   - discovery
   - mysql
example-service:
  image: sit/example-biz-service
  links:
   - discovery
   - mysql
service-gateway:
  image: sit/sit-base-service-gateway
  ports:
   - "9098:9098"
  links:
   - discovery
   - token-service
   - example-service