discovery:
  image: sit/sit-base-service-center
  ports:
   - "9099:9099"
token-service:
  image: sit/sit-base-token-service
  ports:
   - "9090:9090"
  links:
   - discovery
example-service:
  image: sit/example-biz-service
  ports:
   - "8082:8082"
  links:
   - discovery
   - token-service
service-gateway:
  image: sit/sit-base-service-gateway
  ports:
   - "9098:9098"
  links:
   - discovery
   - token-service
   - example-service